// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_GjzJSiETKaiDeJXd8qx7PkCLMJj3ScM',
    appId: '1:176284279183:web:8c429e8a5f63b5cd30abfa',
    messagingSenderId: '176284279183',
    projectId: 'anjuman-committee-abd0d',
    authDomain: 'anjuman-committee-abd0d.firebaseapp.com',
    storageBucket: 'anjuman-committee-abd0d.firebasestorage.app',
    measurementId: 'G-2LQYMF7RH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Va4XjRlScfwztuWWYipBb_9grkVn7yE',
    appId: '1:176284279183:android:d133d9accb60f6bb30abfa',
    messagingSenderId: '176284279183',
    projectId: 'anjuman-committee-abd0d',
    storageBucket: 'anjuman-committee-abd0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgbeHJGAkyS7_eMx9u-yO6T_k2KHHuHgY',
    appId: '1:176284279183:ios:c5e6f30ed51695af30abfa',
    messagingSenderId: '176284279183',
    projectId: 'anjuman-committee-abd0d',
    storageBucket: 'anjuman-committee-abd0d.firebasestorage.app',
    iosBundleId: 'com.anjumancommittee.anjumanCommittee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgbeHJGAkyS7_eMx9u-yO6T_k2KHHuHgY',
    appId: '1:176284279183:ios:c5e6f30ed51695af30abfa',
    messagingSenderId: '176284279183',
    projectId: 'anjuman-committee-abd0d',
    storageBucket: 'anjuman-committee-abd0d.firebasestorage.app',
    iosBundleId: 'com.anjumancommittee.anjumanCommittee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_GjzJSiETKaiDeJXd8qx7PkCLMJj3ScM',
    appId: '1:176284279183:web:6c7a46285e8559d430abfa',
    messagingSenderId: '176284279183',
    projectId: 'anjuman-committee-abd0d',
    authDomain: 'anjuman-committee-abd0d.firebaseapp.com',
    storageBucket: 'anjuman-committee-abd0d.firebasestorage.app',
    measurementId: 'G-C2NS048GDT',
  );
}
