on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
<<<<<<< HEAD
      - # ⬇️ Checkout source
      - uses: actions/checkout@v3

      # ⬇️ Setup Java (Android)
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # ⬇️ Setup Flutter
=======
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'
>>>>>>> 2768e10220b94b591faede200e549e88126df57f
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

<<<<<<< HEAD
      # ⬇️ Install dependencies
      - run: flutter pub get

      # 🔵 Build Android
      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      # 🔵 Build iOS (IPA)
      - name: Build iOS IPA (No Co-Design)
        run: flutter build ios --no-codesign

      # 🔵 Release to GitHub
=======
      - run: flutter build apk --release --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
>>>>>>> 2768e10220b94b591faede200e549e88126df57f
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}






# push to master, main, develop
# pull request on main master